# Generated by Django 3.0.7 on 2020-07-03 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='attached_file',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
    ]
